# Generated by Django 2.2.1 on 2019-05-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='agric',
            field=models.IntegerField(default='', verbose_name='agric'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='bio',
            field=models.IntegerField(default='', verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='english',
            field=models.IntegerField(default='', verbose_name='english'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='math',
            field=models.IntegerField(default='', verbose_name='math'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='student_number',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='student_number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default='', verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='student_number'),
        ),
    ]
