# Generated by Django 2.2.1 on 2019-05-24 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_myaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='marks.Student'),
        ),
    ]
